export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PROFILE_IMG = "SET_PROFILE_IMG";
export const SET_HOME_IMG = "SET_HOME_IMG";
export const SET_HOME_DETAILS = "SET_HOME_DETAILS";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const SET_FILTER_HOMETYPE = "SET_FILTER_HOMETYPE";
export const SET_FILTER_LIFESTYLE = "SET_FILTER_LIFESTYLE";
export const SET_FILTER_AMNETIES = "SET_FILTER_AMNETIES";
export const SET_FILTER_DETAILS = "SET_FILTER_DETAILS";
export const SET_COUNTER= "SET_COUNTER"; 

export const SET_IS_NAV_SEARCH_SHOWN= "SET_IS_NAV_SEARCH_SHOWN"; 